### ISSUE TITLE
application is caching routes

### ISSUE THREAD

**Issue by ajahongir** [darkphnx/coffee_routes#1]
for some reason my application caches routes on client side on development mode,
tried to restart application - no success

when i run 'CoffeeRoutes.routes' on console - everything is well but on client side no changes.
any ideas?

**Comment by darkphnx** [comment]
This is a problem with the way the asset pipeline works in development mode, just run the following and restart your app, you should be back on track:

``` sh
rake tmp:cache:clear
```
